site_name: Contract as a Service
site_url: https://docs.contract-as-a-service.net
use_directory_urls: true

nav:
  - Home: README.md
  - Introduction: intro.md
  - Overview: overview.md
  - Adoption: adoption.md
  - Problem: problem.md
  - Core Concept: core-concept.md
  - Architecture: architecture.md
  - Patterns: patterns.md
  - Business Logic: business-logic.md
  - Contract Design: contract-design.md
  - Reference Examples: reference-examples.md

theme:
  name: material
  features:
    - navigation.expand
#    - navigation.sections
    - navigation.tracking
#    - navigation.top
#    - navigation.tabs
  palette:
    - scheme: default
      primary: custom
      accent: custom
    - scheme: slate
      primary: custom
      accent: custom
  font:
    text: Inter
    code: Roboto Mono

extra_css:
  - extra.css

extra:
  generator: false
